app:
  port: 3003
  url:
    scheme: http
    host: localhost
    port: 3003
  magicNumber: MAGIC_NUMBER
  site:
    logo:
    brand:

db:
  path: /tmp/poex-database-dev

currencies:
  btc:
    defaultNetwork: testnet
    networks:
      mainnet:
        incomingPrivateKey: xprvXXXXX
        outgoingPublicKey: xprvXXXXX
        documentPrice: 200000
        feeMultiplier: 2
      testnet:
        incomingPrivateKey: tprvXXXXX
        outgoingPublicKey: tprvXXXXX
        documentPrice: 100000
        feeMultiplier: 4

mail:
  from:
  to:

nodemailer:
  options:
    service: Gmail
    auth:
      user:
      pass:
